"""Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value
of D?"""


def pentagonal(n):
    return (i * (3 * i - 1) // 2 for i in range(1, n))

if __name__ == "__main__":
    limit = 10000
    l = list(pentagonal(limit))
    s = set(pentagonal(limit))
    for i in range(len(l)):
        for j in range(i, len(l)):
            d = l[j] - l[i]
            n = l[j] + l[i]
            if d in s and n in s:
                print(d)
