"""Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value
of D?"""


def pentagonal(n):
    return (n * (3 * n - 1) // 2 for n in range(1, n))


def task44():
    l = list(pentagonal(10000))
    s = set(l)
    return next(m - n for n in l for m in l
                if m - n in s
                if m + n in s)


if __name__ == "__main__":
    print(task44())
